# 나머지는 참고자료로 읽어보기!!! (시간날 때 정리)
+ 비선형~ 
+ MLP로 손글씨, MNIST 분류는 Colab으로 실습하기

# Artificial Neural Network
__Overfitting__
+ model의 training이 과하게 학습된 경우로 test data나 실제 service에 대해 정확도가 좋지 않은 현상이 발생할 수 있음
    + 즉, training data에 대해 error가 낮아지지만, test data에 대해 error가 높아짐
+ test data의 error가 증가하기 전이나, accuracy가 감소하기 전에 training을 멈추는 것이 바람직함
+ 방지를 위해 test data의 성능이 낮아지기 전에 training을 멈추는 것이 좋지만 underfitting 위험이 있음
    + underfitting보다 overfitting보다 accuracy가 낮음
    + 방지 방법으로 drop out과 early stopping이 있음

## Perceptron
+ 다수의 입력으로부터 하나의 결과를 내보내는 algorithm
+ input value를 가중치와 함께 neural에 전달함
    + 각 input value에는 각각의 가중치가 존재함
        + 각 input value이 가중치와 곱해져 nueral에 보내짐
        + 곱의 전체 합이 threshold를 넘으면 출력 신호 1 또는 그렇지 않은 경우 0을 출력함(step function)  
        + 가중치가 클수록 해당 input value가 중요해짐 

### Single layer perceptron
+ input layer와 output layer로만 이루어져 있음
+ single layer perceptron을 이용해서 AND, NAND, 그리고 OR gate를 쉽게 구현할 수 있음 

In [9]:
# AND gate
# 둘 다 1이면 1
def AND_gate(x1,x2):
    w1 = 0.5
    w2 = 0.5
    b = - 0.7
    res = x1*w1 + x2*w2 + b
    if res <= 0:
        return 0
    else:
        return 1
    
AND_gate(0, 0), AND_gate(0, 1), AND_gate(1, 0), AND_gate(1, 1)

(0, 0, 0, 1)

In [10]:
# OR gate 
# 둘 중 하나가 1이 또는 둘 다 1이면 1 
def OR_gate(x1, x2):
    w1 = 0.6
    w2 = 0.6
    b = - 0.5
    res = x1*w1 + x2*w2 + b
    if res <= 0:
        return 0
    else: 
        return 1 
OR_gate(0, 0), OR_gate(0, 1), OR_gate(1, 0), OR_gate(1, 1)

(0, 1, 1, 1)

In [11]:
# NAND gate
# 둘다 1일 경우 0
def NAND_gate(x1,x2):
    w1 = -0.5
    w2 = -0.5 
    b = 0.7 
    res = x1*w1 + x2*w2 + b
    if res <= 0:
        return 0 
    else:
        return 1 

NAND_gate(0, 0), NAND_gate(0, 1), NAND_gate(1, 0), NAND_gate(1, 1)

(1, 1, 1, 0)

### XOR gate
+ 입력 두 개가 서로 다른 값을 갖고 있을 때만 출력값이 1
+ AND, NAND, OR gate와 달리 single layer perceptron으로 구현하기 힘듦 
    + single layer perceptron은 직선 하나로 두 영역을 나눌 수 있는 문제에 대해서 구현 가능
+ AND, NAND, OR gate를 조합하면 만들 수 있음
    + layer를 더 쌓으면 구현 가능함 -> multi-layer perceptron 

## Multi-layer perceptron(MLP)
+ single-layer perceptron와 달리 입력층과 출력층 사이에 층을 추가함(Hidden layer)
    + MLP는 hidden layer가 1개 이상인 perceptron임
    + hidden layer가 2개 이상인 neural network를 Deep Neural Network(DNN)라고 함
        + training시키는 ANN이 DNN일 경우 Deep learning임

__Training__
+ machine이 weight를 스스로 찾아내도록 자동화시키야 하는 단계

## XOR problem with Single layer perceptron

In [12]:
import torch
import torch.nn as nn

In [13]:
# this code just setting for run on GPU, now variable 'device' state is CPU
device = 'cuda' if torch.cuda.is_available() else 'cpu'
torch.manual_seed(1)

if device == 'cuda':
    torch.cuda.manual_seed_all(1)

In [14]:
# XOR data 
X = torch.FloatTensor([[0, 0], [0, 1], [1, 0], [1, 1]]).to(device)
Y = torch.FloatTensor([[0], [1], [1], [0]]).to(device)

# set to single layer perceptron, while activation function is sigmoid function
linear = nn.Linear(2,1, bias = True)
sig = nn.Sigmoid()
mod = nn.Sequential(linear, sig).to(device)

# cost function(cross entropy(binary classification problem)) and optimizer
criterion = nn.BCELoss().to(device)
opt = torch.optim.SGD(mod.parameters(), lr=1)

In [15]:
# run about epoch 10000 times
for step in range(10001):
    opt.zero_grad()
    hyp = mod(X)
    
    # cost function 
    cost = criterion(hyp, Y)
    cost.backward()
    opt.step()
    
    if step % 100 == 0:
        print(step, cost.item())
        
# 10000번 epoch가 되어도 cost가 줄어들지 않는 이유는 single layer perceptron으로 XOR 문제를 풀 수 없기 때문

0 0.7018222212791443
100 0.6931473016738892
200 0.6931471824645996
300 0.6931471824645996
400 0.6931471824645996
500 0.6931471824645996
600 0.6931471824645996
700 0.6931471824645996
800 0.6931471824645996
900 0.6931471824645996
1000 0.6931471824645996
1100 0.6931471824645996
1200 0.6931471824645996
1300 0.6931471824645996
1400 0.6931471824645996
1500 0.6931471824645996
1600 0.6931471824645996
1700 0.6931471824645996
1800 0.6931471824645996
1900 0.6931471824645996
2000 0.6931471824645996
2100 0.6931471824645996
2200 0.6931471824645996
2300 0.6931471824645996
2400 0.6931471824645996
2500 0.6931471824645996
2600 0.6931471824645996
2700 0.6931471824645996
2800 0.6931471824645996
2900 0.6931471824645996
3000 0.6931471824645996
3100 0.6931471824645996
3200 0.6931471824645996
3300 0.6931471824645996
3400 0.6931471824645996
3500 0.6931471824645996
3600 0.6931471824645996
3700 0.6931471824645996
3800 0.6931471824645996
3900 0.6931471824645996
4000 0.6931471824645996
4100 0.6931471824645996
4200

In [16]:
# check predicted values
with torch.no_grad():
    hyp = mod(X)
    pred = (hyp>0.5).float()
    acc = (pred==Y).float().mean()
    print(f'Hypothesis: \n {hyp.detach().cpu().numpy()}')
    print(f'Predicted: \n {pred.detach().cpu().numpy()}')
    print(f'Real values(Y): \n {Y.cpu().numpy()}')
    print(f'Accuracy: \n {acc.item()}')
    

Hypothesis: 
 [[0.5]
 [0.5]
 [0.5]
 [0.5]]
Predicted: 
 [[0.]
 [0.]
 [0.]
 [0.]]
Real values(Y): 
 [[0.]
 [1.]
 [1.]
 [0.]]
Accuracy: 
 0.5


## BackPropagation
+ forward propagation을 통해 산출된 output을 실제값과의 error가 최소가 되도록 
+ 각 layer에서 입력되는 값에 곱해지는 weighted와 bias를 계산하여 업데이트함\
참고: https://m.blog.naver.com/samsjang/221033626685
### Forward Propagation
<img src="https://wikidocs.net/images/page/37406/nn2_final_final.PNG">

+ 위 그림에서 $x_1, x_2$는 입력값이고 $o_1, o_2$은 출력값일 때, 
    + 각 입력은 input layer에서 hidden layer로 향하면서 각 가중치 $w_i$를 곱해지고 
    + 가중합으로 계산되어 hidden layer의 sigmoid function의 입력값이 됨($z_1, z_2$)
        + e.g. $z_1 = w_1x_1+w_2x_2, \ z_2 = w_3x_3+w_4x_4 $
    + sigmoid fuction에서 return된 값 $h_1, \ h_2$는 다음과 같다
        + e.g. $h_1 = sigmoid(z_1), \ h_2 = sigmoid(z_2)$
    + return된 값을 output layer로 향하게 되고 다시 각 해당 가중치와 곱해져 가중합이 되며, sigmoid function의 입력값이 됨
        + e.g. $z_3 = w_5h_1+w_6h_2, \ z_4 = w_7h_1+w_8h_2$
    + 계산된 $z_3, \ z_4$는 output layer에서 sigmoid function을 통해 최종 출력값 $o_1, \ o_2$가 됨
        + e.g. $o_1 = sigmoid(z_3), \ o_2 = sigmoid(z_4)$ 
+ 최종값인 출력값 $o_1, \ o_2$(예측값)는 error를 계산하기 위한 loss function으로 MSE를 이용함
    + e.g. $E_{o_1} = \frac{1}{2} (target_{o_1}-output_{o_1})^2, \ E_{o_2} = \frac{1}{2} (target_{o_2}-output_{o_2})^2, \ E_{total}=\sum_{i=1}^N E_{o_i}$

### Back Propagation
+ back propagation은 output layer에서 input layer로 계산하면서 weighted를 update함(forward -> back)
    + output layer 이전의 hidden layer를 N층이라고 하면 output layer와 N층 사이의 weighted를 업데이트(back propagation 1 step)
    + 그 다음 N층과 N층 사이의 weighted를 update하면서 나머지 weighted를 update해 나감(back propagation 2 step)

__Back propagation 1 step__\
<img src="https://wikidocs.net/images/page/37406/nn3_final.PNG">

+ chain rule을 이용함 

+ 위 그림에서 가중치 $w_5, w_6, w_7, w_8$을 update해야함. 
    + e.g. 가중치 $w_5$에 대한 update 
        + $\frac{\partial E_{total}}{\partial w_5} = \frac{\partial E_{total}}{\partial o_1} \times \frac{\partial o_1}{\partial z_3} \times \frac{\partial z_3}{\partial w_5}$
        + 다음으로 update하기 위한 gradient descent(optimization algorithm 이용)
            + $w_5^+ = w_5 - \alpha \frac{\partial E_{total}}{{\partial w_5}}$
+ 나머지도 같은 방식으로 weighted를 update한다

__Back propagation 2 step__\
<img src="https://wikidocs.net/images/page/37406/nn4.PNG">

+ e.g. 가중치 $w_1$에 대한 update
    + $\frac{\partial E_{total}}{\partial w_1} = \frac{\partial e_{total}}{\partial h_1} \times \frac{\partial h_1}{\partial z_1} \times \frac{\partial z_1}{\partial w_1}$
    + 그 다음으로 update를 위해 gradient descent를 함
        + $w_5^+ = w_5 - \alpha \frac{\partial E_{total}}{\partial w_5}$
    + 이외 다른 weighted도 같은 방식으로 계산


__back propagation을 진행 후 error가 감소했는지 확인하기 위해 forward propagation을 진행하여 산출한 predicted와 real value의 error를 확인__

## solve XOR Problem with MLP

In [17]:
# XOR data
X = torch.FloatTensor([[0, 0], [0, 1], [1, 0], [1, 1]])
Y = torch.FloatTensor([[0], [1], [1], [0]])

In [18]:
# model(MLP)
mod = nn.Sequential(
    nn.Linear(2,10,bias = True), # input layer = 2, hidden layer = 10 
    nn.Sigmoid(),
    nn.Linear(10,10,bias = True), # hidden layer = 10, hidden layer = 10
    nn.Sigmoid(),
    nn.Linear(10,10,bias = True), # hidden layer = 10, hidden layer = 10
    nn.Sigmoid(),
    nn.Linear(10,1,bias = True), # input layer = 10, outpt layer = 1
    nn.Sigmoid()
)

# define cost function, optimier and number of epochs
criterion = nn.BCELoss()
opt = torch.optim.SGD(mod.parameters(), lr=1)
n_epoch = 10000

# iterate as much as epoch with back propagation

for epoch in range(n_epoch+1):
    opt.zero_grad()
    # forward operation
    hyp = mod(X)
    
    cost = criterion(hyp,Y)
    cost.backward()
    opt.step()
    
    if epoch % 100 == 0:
        print(f'Epoch: {epoch} Cost: {cost.item()} ')
    

Epoch: 0 Cost: 0.7555788159370422 
Epoch: 100 Cost: 0.6931402683258057 
Epoch: 200 Cost: 0.6931398510932922 
Epoch: 300 Cost: 0.6931394338607788 
Epoch: 400 Cost: 0.6931390762329102 
Epoch: 500 Cost: 0.6931387186050415 
Epoch: 600 Cost: 0.6931383013725281 
Epoch: 700 Cost: 0.6931377649307251 
Epoch: 800 Cost: 0.6931372880935669 
Epoch: 900 Cost: 0.6931368708610535 
Epoch: 1000 Cost: 0.6931363344192505 
Epoch: 1100 Cost: 0.6931357979774475 
Epoch: 1200 Cost: 0.6931352615356445 
Epoch: 1300 Cost: 0.6931347250938416 
Epoch: 1400 Cost: 0.693134069442749 
Epoch: 1500 Cost: 0.6931334733963013 
Epoch: 1600 Cost: 0.693132758140564 
Epoch: 1700 Cost: 0.6931321620941162 
Epoch: 1800 Cost: 0.6931313276290894 
Epoch: 1900 Cost: 0.6931305527687073 
Epoch: 2000 Cost: 0.6931297779083252 
Epoch: 2100 Cost: 0.6931288838386536 
Epoch: 2200 Cost: 0.6931278705596924 
Epoch: 2300 Cost: 0.693126916885376 
Epoch: 2400 Cost: 0.69312584400177 
Epoch: 2500 Cost: 0.6931246519088745 
Epoch: 2600 Cost: 0.693123519

In [20]:
# evaluate predicted value from trained MLP
with torch.no_grad():
    hyp = mod(X)
    pred = (hyp > 0.5).float()
    acc = (pred == Y).float().mean()
    print(f'Outputs from model(hypothesis): \n {hyp.detach().cpu().numpy()}')
    print(f'Predicted value from model: \n {pred.detach().cpu().numpy()}')
    print(f'Real values: \n {Y.cpu().numpy()}')
    print(f'Accuracy: \n {acc.item()}')

Outputs from model(hypothesis): 
 [[1.9867101e-04]
 [9.9977762e-01]
 [9.9982017e-01]
 [2.1193606e-04]]
Predicted value from model: 
 [[0.]
 [1.]
 [1.]
 [0.]]
Real values: 
 [[0.]
 [1.]
 [1.]
 [0.]]
Accuracy: 
 1.0
