# Vector, Matrix, and Tensor
+ vector: dimension 없는 값를 scalar 차원으로 구성된 값
+ matrix: 2-dimension으로 구성되어 있는 값
+ tensor: 3-dimension으로 구성되어 있는 값
\
\
__DL을 할때 중요한 부분은 다루고 있는 matrix 또는 tensor 크기를 고려__
+ 2D tensor: $|t| = (batch \ size, \ dim)$
+ 3D tensor: $|t| = (batch \ size , \ width, \ height)$
    + 일반적인 vision 분야에서 다루게 됨
    + NLP 경우: $|t| = (batch \ size , \ length, \ dim)$ 
        + (batch size, length of sentence, dimension of vector of word)

In [1]:
# make tensor with Numpy
import numpy as np 
import torch

In [2]:
# 1D with numpy
t = np.array([0.,1.,2,3.,4.,5.,6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [3]:
# print rand and shape
print('rank of t: ', t.ndim) # 몇 차원인지
print('shape of t: ', t.shape) # 크기가 얼마인지

rank of t:  1
shape of t:  (7,)


In [4]:
# 2D with Numpy
t = np.array([[1.,2.,3.], 
              [4.,5.,6.],
              [7.,8.,9.],
              [10.,11.,12.]])
print(t)

print(f"Rank of t: {t.ndim}")
print(f"Shap of t: {t.shape}")

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
Rank of t: 2
Shap of t: (4, 3)


In [5]:
# 1D with Pytorch
t = torch.FloatTensor([0.,1.,2.,3.,4.,5.,6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [6]:
print(t.dim()) # 차원
print(t.shape) # = size(), 크기  

1
torch.Size([7])


In [7]:
# 2D with Pytorch
t = torch.FloatTensor([[1.,2.,3.],
                       [4.,5.,6.],
                       [7.,8.,9.],
                       [10.,11.,12.]])

print(t.dim())
print(t.size())

2
torch.Size([4, 3])


In [8]:
# Broadcasting: 서로 다른 vector(or matrix)의 크기를 맞춰 operation을 수행하게 만듦
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([[2,2]])

print(m1+m2)

tensor([[5., 5.]])


In [9]:
# vector and scalar
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([3])
# pytorch의 경우 m2의 크기를 m1에 맞게 크기를 변경하여 연산 수행
print(m1+m2)

tensor([[4., 5.]])


In [10]:
# vector operation
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([[3],[4]])

# pytorch의 경우 두 벡터의 크기가 달라도 크기를 맞춰 연산을 수행함
print(m1+m2) 

tensor([[4., 5.],
        [5., 6.]])


In [11]:
# Difference between matrix multiplication and multiplication

m1 = torch.FloatTensor([[1,2],[3,4]])
m2 = torch.FloatTensor([[1],[2]])

print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1

print(m1.matmul(m2)) # multiplication, 2 x 1

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [12]:
# element-wise mutiplication: 동일한 크기의 행렬이 동일한 위치에 있는 원소끼리 곱하는 것

print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1 * m2) # 2 x 2
print(m1.mul(m2)) # same with operator *

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


In [13]:
# Mean 
t = torch.FloatTensor([1,2])
print(t.mean())

tensor(1.5000)


In [14]:
t = torch.FloatTensor([[1,2],[3,4]])

print(t.mean())
print(t.mean(dim=0)) # dim=0은 첫 번째 차원을 의미함 즉, 행임 e.g. 2 by 2 matrix -> 1 by 2, same with (2,)인 vector
print(t.mean(dim=1)) # 열이 제거된 tensor가 되어야 함

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])


In [15]:
# summation
t = torch.FloatTensor([[1,2],[3,4]])
print(t) # 2 by 2  matrix
print(t.sum())
print(t.sum(dim=0)) # 행 제거
print(t.sum(dim=1)) # 열 제거
print(t.sum(dim=-1))

tensor([[1., 2.],
        [3., 4.]])
tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


In [16]:
# maximum value 
print(t.max())
print(t.max(dim=0)) # 행 제거, 열 기준의 최댓값 column 1의 최댓값은 3이고 column 2의 최댓값은 4이므로 3,4가 출력
print(t.max(dim=1)) # 열 제거, 행 기준의 최댓값 row 1의 최댓값은 2이고 row 2의 최댓값은 4이므로 2, 4가 출력

print(t.max(dim=0)[0])
print(t.max(dim=1)[0])

tensor(4.)
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
tensor([3., 4.])
tensor([2., 4.])


# View
+ 원소의 수를 유지하면서 tensor의 크기 변경
+ numpy에서 reshape와 같은 역할함, 크기를 변경해줌

__Rules in view__
+ view는 기본적으로 변경 전과 후의 tensor 안의 개수가 유지되어야 함
+ torch의 view는 size가 -1로 설정되면 다른 차원으로부터 해당 값을 유추 
    + 유추할 때 총 원소의 개수가 reshape 이전 원소의 개수가 동일해야 함 

In [17]:
# reshape in numpy VS  view in torch
t = np.array([[[0,1,2],
               [3,4,5]],
              [[6,7,8],
              [9,10,11]]]) # 3-dim tensor
print(t)
print(f't shape: {t.shape}')

ft = torch.FloatTensor(t)
print(f'ft shape: {ft.shape}')

# 3 dim tensor to 2 dim tensor
print(f'3 dim tensor to 2 dim tensor \n {ft.view([-1,3])}') # reshape to (?,3)
print(f'check size after change: {ft.view([-1,3]).shape}') # -1은 첫번째 dim은 임의로 설정하겠다는 의미임

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
t shape: (2, 2, 3)
ft shape: torch.Size([2, 2, 3])
3 dim tensor to 2 dim tensor 
 tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
check size after change: torch.Size([4, 3])


# Squeeze
+ dimension이 1인 경우 해당 차원을 제거한다

# Unsqueeze
+ squeeze와 반대
+ 특정 위치에 1인 dimension을 추가한다

In [18]:
ft = torch.FloatTensor([[0],[1],[2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [19]:
# squeeze
print(ft.squeeze())
print(f'shape after squeeze: {ft.squeeze().shape}')

tensor([0., 1., 2.])
shape after squeeze: torch.Size([3])


In [20]:
# unsqueeze
print(ft.unsqueeze(0)) # 첫 번째 차원 unsqueeze
print(ft.unsqueeze(0).shape)

tensor([[[0.],
         [1.],
         [2.]]])
torch.Size([1, 3, 1])


In [21]:
# unsqueeze same with view
print(ft.view(1,-1)) # 2 dim으로 바꾸고 싶으면서 첫 번째 dim은 1이기 원한다면 view에 (1,-1)인자 사용
print(ft.view(1,-1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [22]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[[0.]],

        [[1.]],

        [[2.]]])
torch.Size([3, 1, 1])


# Type casting
+ 자료형을 변환하는 것

In [23]:
lt = torch.LongTensor([1,2,3,4])
print(lt.dtype)

torch.int64


In [24]:
# change type to float
print(lt.float())
print(lt.float().dtype)

tensor([1., 2., 3., 4.])
torch.float32


# Concatenate
+ 두 tensor를 연결
+ DL에서 두 tensor를 연결하여 입력으로 사용함. 
    + 두 정보를 모두 사용한다는 의미임

In [26]:
x = torch.FloatTensor([[1,2],
                       [3,4]])
y = torch.FloatTensor([[5,6],
                       [7,8]])

print(torch.cat([x,y],dim=0)) # 첫 번째 차원을 늘림, 2 by 2 to 4 by 2
print(torch.cat([x,y],dim=1)) # 2 by 2 to 2 by 4

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


# Stacking
+ concatenate를 하는 또 다른 방법임
+ 일반적인 concatenate보다 더 많은 연산을 포함하고 있음

In [32]:
x = torch.FloatTensor([1,4])
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])

print(torch.stack([x,y,z]))
print(f'same with above \n {torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0)} \n')

# increase to 2 dimension
print(torch.stack([x,y,z], dim=1))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
same with above 
 tensor([[1., 4.],
        [2., 5.],
        [3., 6.]]) 

tensor([[1., 2., 3.],
        [4., 5., 6.]])


# Ones_like and zeros_like
+ Ones_like: 1로 채워진 tensor
+ zeros_like: 0으로 채워진 tensor

In [36]:
x = torch.FloatTensor([[0,1,2],[2,1,0]])
print(f'{x} \n')

# fill up with one
print(f'{torch.ones_like(x)} \n')

# fill up with zero
print(torch.zeros_like(x))

tensor([[0., 1., 2.],
        [2., 1., 0.]]) 

tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

tensor([[0., 0., 0.],
        [0., 0., 0.]])


# In-place Operation
+ 덮어쓰기 연산

In [37]:
x = torch.FloatTensor([[1,2],[3,4]])

print(x.mul(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])


In [38]:
# in place operator _ (under bar)
print(x.mul_(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
